<?php
require_once '../bootstrap.php';
require_once('../lib/tcpdf/tcpdf.php');
//authentication
LogInCheck();
$server_name = "localhost";
$user_name = "root";
$password = "";
$database = "stockphp";

$conn = new mysqli($server_name, $user_name, $password, $database);






// Function to generate the PDF content
function generatePDFContent($conn)
{
    $content = '';

    // Query to fetch data
    $sql = "SELECT * FROM item, department, supplier WHERE supplied_at = CURDATE()";
    $result = $conn->query($sql);

    // Table header
    $content .= '<tr>
                    <th width="10%"><i>SLNO</i></th>
                    <th width="20%"><i>NAME</i></th>
                    <th width="30%"><i>DEPARTMENT</i></th>
                    <th width="30%"><i>SUPPLIER</i></th>
                </tr>';

    $i = 1;
    while ($row = $result->fetch_assoc()) {
        $content .= "<tr>
                        <td>{$i}</td>
                        <td>{$row['item_name']}</td>
                        <td>{$row['dept_name']}</td>
                        <td>{$row['supplier_name']}</td>
                    </tr>";
        $i++;
    }

    return $content;
}

// Create TCPDF instance
$pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document properties
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetTitle("Item List");
$pdf->SetHeaderData('', '', 'DAILY ITEM REPORT SYSTEM', 'Generated by admin');
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
$pdf->SetDefaultMonospacedFont('helvetica');
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
$pdf->SetMargins(PDF_MARGIN_LEFT, 10, PDF_MARGIN_RIGHT);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->SetAutoPageBreak(TRUE, 10);
$pdf->SetFont('helvetica', '', 10);

// Add a page
$pdf->AddPage();

// Generate PDF content
$pdfContent = '<div>
                <h2 align="center">DAILY ITEM REPORT SYSTEM</h2>
                <h4>GENERATED BY admin</h4>
                <h4>' . date('d-m-y H:i:s') . '</h4>
                <table border="1" cellspacing="0" cellpadding="3">';

// Add generated content
$pdfContent .= generatePDFContent($conn);

$pdfContent .= '</table></div>';
$pdf->writeHTML($pdfContent);

// Output PDF
$pdf->Output('daily_items_list.pdf', 'I');

// Close database connection
$conn->close();
?>
